# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 588d1d3da49f2a23db9b4e0211913694f726ceecd2078739eae22eafa32ebe660be69ddcb8c86786c192485d56b8ddb1ee00eed8c2d0733e7ee90c8185159232

test:
  secret_key_base: 84ed583e13e87c6d9a8ed0fe08b42d76d9b97eb31ee96bf610a8d9e17f3636e5f92606a5d54a612940c509d2bd306245de5460a824c7aa56fde3999a784a8049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
